[2024-12-04T23:20:37.301+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T23:20:37.324+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:20:34.870088+00:00 [queued]>
[2024-12-04T23:20:37.337+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:20:34.870088+00:00 [queued]>
[2024-12-04T23:20:37.338+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-04T23:20:37.357+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2024-12-04 23:20:34.870088+00:00
[2024-12-04T23:20:37.368+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=810) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T23:20:37.369+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_data', 'manual__2024-12-04T23:20:34.870088+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpbsplzzzd']
[2024-12-04T23:20:37.370+0000] {standard_task_runner.py:72} INFO - Started process 812 to run task
[2024-12-04T23:20:37.370+0000] {standard_task_runner.py:105} INFO - Job 99: Subtask extract_data
[2024-12-04T23:20:37.440+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:20:34.870088+00:00 [running]> on host f697cea74b34
[2024-12-04T23:20:37.740+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T23:20:34.870088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T23:20:34.870088+00:00'
[2024-12-04T23:20:37.741+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-04T23:20:37.742+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-04T23:20:37.743+0000] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2024-12-04 23:20:37.325805+00:00
[2024-12-04T23:20:37.744+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-12-04T23:20:37.745+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T23:20:37.746+0000] {logging_mixin.py:190} INFO - Erro ao ler o arquivo: [Errno 2] No such file or directory: '/opt/***/dados/data.csv'
[2024-12-04T23:20:37.747+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-04T23:20:37.759+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T23:20:37.760+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_data, run_id=manual__2024-12-04T23:20:34.870088+00:00, execution_date=20241204T232034, start_date=20241204T232037, end_date=20241204T232037
[2024-12-04T23:20:37.773+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-04T23:20:37.774+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-04T23:20:37.775+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2024-12-04 23:20:34.887455+00:00
[2024-12-04T23:20:37.776+0000] {logging_mixin.py:190} INFO - Task hostname:f697cea74b34 operator:PythonOperator
[2024-12-04T23:20:37.828+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-04T23:20:37.857+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-04T23:20:37.862+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
