[2024-12-04T23:34:37.624+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T23:34:37.645+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:34:35.124807+00:00 [queued]>
[2024-12-04T23:34:37.656+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:34:35.124807+00:00 [queued]>
[2024-12-04T23:34:37.657+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-04T23:34:37.676+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2024-12-04 23:34:35.124807+00:00
[2024-12-04T23:34:37.687+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1036) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T23:34:37.689+0000] {standard_task_runner.py:72} INFO - Started process 1038 to run task
[2024-12-04T23:34:37.689+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_data', 'manual__2024-12-04T23:34:35.124807+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpgz4oj1e5']
[2024-12-04T23:34:37.691+0000] {standard_task_runner.py:105} INFO - Job 111: Subtask extract_data
[2024-12-04T23:34:37.766+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:34:35.124807+00:00 [running]> on host f697cea74b34
[2024-12-04T23:34:38.081+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T23:34:35.124807+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T23:34:35.124807+00:00'
[2024-12-04T23:34:38.082+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-04T23:34:38.083+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-04T23:34:38.084+0000] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2024-12-04 23:34:37.646350+00:00
[2024-12-04T23:34:38.085+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-12-04T23:34:38.085+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T23:34:38.087+0000] {logging_mixin.py:190} INFO - Erro ao ler o arquivo: [Errno 2] No such file or directory: '/opt/***/dados/data.csv'
[2024-12-04T23:34:38.088+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-04T23:34:38.102+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T23:34:38.103+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_data, run_id=manual__2024-12-04T23:34:35.124807+00:00, execution_date=20241204T233435, start_date=20241204T233437, end_date=20241204T233438
[2024-12-04T23:34:38.118+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-04T23:34:38.119+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-04T23:34:38.121+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2024-12-04 23:34:35.189058+00:00
[2024-12-04T23:34:38.121+0000] {logging_mixin.py:190} INFO - Task hostname:f697cea74b34 operator:PythonOperator
[2024-12-04T23:34:38.148+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-04T23:34:38.178+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-04T23:34:38.181+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
