[2024-12-04T23:03:42.632+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T23:03:42.662+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:03:38.848398+00:00 [queued]>
[2024-12-04T23:03:42.699+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:03:38.848398+00:00 [queued]>
[2024-12-04T23:03:42.703+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-04T23:03:42.749+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2024-12-04 23:03:38.848398+00:00
[2024-12-04T23:03:42.768+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=534) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T23:03:42.772+0000] {standard_task_runner.py:72} INFO - Started process 536 to run task
[2024-12-04T23:03:42.773+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_data', 'manual__2024-12-04T23:03:38.848398+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmplg1hcosl']
[2024-12-04T23:03:42.775+0000] {standard_task_runner.py:105} INFO - Job 85: Subtask extract_data
[2024-12-04T23:03:42.855+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:03:38.848398+00:00 [running]> on host f697cea74b34
[2024-12-04T23:03:43.265+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T23:03:38.848398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T23:03:38.848398+00:00'
[2024-12-04T23:03:43.267+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-04T23:03:43.268+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-04T23:03:43.269+0000] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2024-12-04 23:03:42.663929+00:00
[2024-12-04T23:03:43.270+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-12-04T23:03:43.271+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T23:03:43.273+0000] {logging_mixin.py:190} INFO - Erro ao ler o arquivo: [Errno 2] No such file or directory: '/opt/***/dados/dados_***.csv'
[2024-12-04T23:03:43.274+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-04T23:03:43.291+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T23:03:43.292+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_data, run_id=manual__2024-12-04T23:03:38.848398+00:00, execution_date=20241204T230338, start_date=20241204T230342, end_date=20241204T230343
[2024-12-04T23:03:43.309+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-04T23:03:43.310+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-04T23:03:43.311+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2024-12-04 23:03:38.887124+00:00
[2024-12-04T23:03:43.312+0000] {logging_mixin.py:190} INFO - Task hostname:f697cea74b34 operator:PythonOperator
[2024-12-04T23:03:43.354+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-04T23:03:43.403+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-04T23:03:43.407+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
