[2024-12-04T23:24:34.603+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T23:24:34.626+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:24:31.796146+00:00 [queued]>
[2024-12-04T23:24:34.637+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:24:31.796146+00:00 [queued]>
[2024-12-04T23:24:34.639+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-04T23:24:34.655+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2024-12-04 23:24:31.796146+00:00
[2024-12-04T23:24:34.665+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=875) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T23:24:34.667+0000] {standard_task_runner.py:72} INFO - Started process 877 to run task
[2024-12-04T23:24:34.667+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_data', 'manual__2024-12-04T23:24:31.796146+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpmyzd16s8']
[2024-12-04T23:24:34.668+0000] {standard_task_runner.py:105} INFO - Job 103: Subtask extract_data
[2024-12-04T23:24:34.727+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.extract_data manual__2024-12-04T23:24:31.796146+00:00 [running]> on host f697cea74b34
[2024-12-04T23:24:35.009+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T23:24:31.796146+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T23:24:31.796146+00:00'
[2024-12-04T23:24:35.011+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-04T23:24:35.012+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-04T23:24:35.013+0000] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2024-12-04 23:24:34.627104+00:00
[2024-12-04T23:24:35.014+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-12-04T23:24:35.015+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T23:24:35.017+0000] {logging_mixin.py:190} INFO - Erro ao ler o arquivo: [Errno 2] No such file or directory: '/opt/***/dados/data.csv'
[2024-12-04T23:24:35.018+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-04T23:24:35.031+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T23:24:35.033+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_data, run_id=manual__2024-12-04T23:24:31.796146+00:00, execution_date=20241204T232431, start_date=20241204T232434, end_date=20241204T232435
[2024-12-04T23:24:35.047+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-04T23:24:35.047+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-04T23:24:35.048+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2024-12-04 23:24:31.832026+00:00
[2024-12-04T23:24:35.049+0000] {logging_mixin.py:190} INFO - Task hostname:f697cea74b34 operator:PythonOperator
[2024-12-04T23:24:35.086+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-04T23:24:35.115+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-04T23:24:35.119+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
